#!/bin/bash

ANTLR=./antlr-4.13.2-complete.jar

if [ "$1" == "gen" ]; then
    java -jar $ANTLR -Dlanguage=Python3 -o output Ansiipythonium.g4
elif [ "$1" == "run" ]; then
    python3 main.py "$2"
    if [ ! -f temp.ll ]; then
        exit 1
    fi

    llc temp.ll -o temp.s
    if [ ! -f temp.s ]; then
        exit 1
    fi

    clang -no-pie temp.s -o program
    rm temp.s temp.ll
    ./program
fi

