#!/bin/bash

ANTLR=./antlr-4.13.2-complete.jar

if [ "$1" == "gen" ]; then
    java -jar $ANTLR -Dlanguage=Python3 -o output Ansiipythonium.g4
elif [ "$1" == "run" ]; then
    python3 main.py "$2" | llc -o temp.s
    clang -no-pie temp.s -o program
    rm temp.s
    ./program
fi

